_schema: _schema
source: /web/public/
paths:
  uploads: uploads
  static: ''
collections_config:
  web_public_admin:
    path: web/public/admin
    name: Web Public Admin
    icon: bath_public_large
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Europe/Prague
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
